bookings/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from bookings.index_views import IndexView
from bookings.crate_views import CrateDetailView, CrateListView, CrateStatsView
from bookings.person_views import PersonView
from bookings.inst_views import InstView, InstListView, InstStatsView
from bookings.booking_views import BookingView, BookingTypesView
from bookings.comment_views import CommentView
from bookings.stats_views import StatsView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^crate/(?P<pk>[-_\w]+)/$', CrateDetailView.as_view(), name='crate'),
    url(r'^crate_stats/(?P<pk>[-_\w]+)/$', CrateStatsView.as_view(), name='crate_stats'),
    url(r'^crates/$', CrateListView.as_view(), name='crates'),
    url(r'^person/(?P<pk>[-_\w]+)/$', PersonView.as_view(), name='person'),
    url(r'^inst/(?P<pk>[-_\w]+)/$', InstView.as_view(), name='inst'),
    url(r'^inst_stats/(?P<pk>[-_\w]+)/$', InstStatsView.as_view(), name='inst_stats'),
    url(r'^insts/$', InstListView.as_view(), name='insts'),
    #url(r'^booking/$', BookingView.as_view(), name='booking'),
    url(r'^booking/(?P<pk>[-_\w]+)/$', BookingView.as_view(), name='booking'),
    url(r'^booking_types/(?P<pk>[-_\w]+)/$', BookingTypesView.as_view(), name='booking_types'),
    #url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^comment/(?P<pk>[-_\w]+)/$', CommentView.as_view(), name='comment'),
    # static information pages
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name="about"),
    url(r'^help$', TemplateView.as_view(template_name='help.html'), name="help"),
    url(r'^stats$', StatsView.as_view(), name="stats"),
    )

cbs/urls.py
from django.conf.urls import patterns, include, url
from django.http import HttpResponse

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rooms.views.home', name='home'),
    # url(r'^rooms/', include('rooms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^bookings/', include('bookings.urls')),
    
    url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain"))
)

bookings/models.py
from django.utils.encoding import smart_unicode
from django.db import models

# use json to store recents
import json

# 'CrateType's define hierarchies of types of Crate, e.g. 'Room', 'Building', 'Site'

class CrateType(models.Model):        
    name = models.CharField('Name', max_length=100, blank=True)
    parent_crate_type = models.ForeignKey('self', blank=True, null=True)

    def __unicode__(self):
        return "Crate type: " + self.name

# 'Crate's are the items that are bookable, or may contain other 'Crates'

class Crate(models.Model):
    id = models.CharField('Crate id', max_length=30, primary_key=True)
    crate_type = models.ForeignKey(CrateType, verbose_name='Type')
    parent_crate = models.ForeignKey('self', blank=True, null=True)
    short_name = models.CharField('Short name (32 max)', max_length=32)
    name = models.CharField('Name', max_length=100)
    map_url =  models.CharField('Link to map', max_length=1000, blank=True, null=True)
    description = models.TextField('Description', max_length=2000, blank=True, null=True)
    location = models.CharField('Location', max_length=100, blank=True, null=True)
    calendar_id = models.CharField('Calendar id', max_length=100, blank=True, null=True)
    calendar_web_color = models.CharField('Calendar web colour', max_length=30, blank=True, null=True)
    calendar_iframe_color = models.CharField('Calendar iframe colour', max_length=30, blank=True, null=True)
    provisional_calendar_id = models.CharField('Provisional Calendar id', max_length=100, blank=True, null=True)
    #calendar_html = models.CharField('Calendar embed html', max_length=1024, blank=True)
    calendar_link = models.CharField('Link to Calendar', max_length=1024, blank=True, null=True)
    email = models.CharField('Email for Approvals', max_length=60, blank=True, null=True)
    calendar_list = models.CharField('Comma separated list of Crate ids for multiple calendars', max_length=300, blank=True, null=True)
    calendar_list_html = models.CharField('Google iframe for multiple calendars', max_length=2000, blank=True, null=True)
    image_list = models.CharField('Comma separated list of image filenames', max_length=300, blank=True, null=True)
    
    def __unicode__(self):
        return "Crate: " + self.name

class CrateOwner(models.Model):
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    instid = models.CharField('Institution id', max_length=15)
    
    def __unicode__(self):
        return self.crate.id+":"+self.instid
        
# A simple list of permission types, used by Rule above
class Permission(models.Model):
    name = models.CharField('Permission name', max_length=32)
    description = models.TextField('Description', max_length=1024)
    index = models.PositiveIntegerField('Permission precendence (1 is highest)')
    
    def __unicode__(self):
        return self.name

# 'Rule's can be checked to confirm permission current user has for current crate
# e.g. 'Admin', 'View', 'Book', 'RepeatBook', 'Approve'

class Rule(models.Model):
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    permission = models.ForeignKey(Permission, verbose_name='Permission')
    instid = models.CharField('Inst id', max_length=16, blank=True, null=True)
    userid = models.CharField('CRSid', max_length=16, blank=True, null=True)
    groupid = models.CharField('Group id', max_length=16, blank=True, null=True)

    def __unicode__(self):
        return 'Rule for crate: ' + self.crate.id

class Reference(models.Model):
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    keyname = models.CharField('Other system key *name* (e.g. PlanOn id)', max_length=16, blank=False)
    keyvalue = models.CharField('Other system reference *value* (i.e. room id)', max_length=30, blank=False)

    def __unicode__(self):
        return self.crate.id + '['+self.keyname+','+self.keyvalue+']'

# 'Comments' can be associated with 'Crates', e.g. a 'Room' could have a noticeboard
class Comment(models.Model):
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    userid = models.CharField('User id', max_length=50)
    user_name = models.CharField('User name', max_length=50, blank=True, null=True)
    timestamp = models.DateTimeField()
    text = models.TextField('Comment', max_length=1024)
    # index is used to 'pin' the comment at the top of the display list
    index = models.PositiveIntegerField('Index', blank=True, null=True)
    
    def __unicode__(self):
        return 'Comment: '+self.userid+'(' + self.crate.id + ')'

class CrateAttributeType(models.Model):
    id = models.CharField('Type id', max_length=30, primary_key=True)
    crate_type = models.ForeignKey(CrateType, verbose_name='Type')
    name = models.CharField('Name', max_length=100)
    is_integer = models.BooleanField('Is integer')

    def __unicode__(self):
        return '(' + self.crate_type.name + ',' + self.name + ')'

# All crates have the base attributes as per the Crate class
# Plus additional attributes can be stored in this class    
class CrateAttribute(models.Model):
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    attribute_type = models.ForeignKey(CrateAttributeType, verbose_name='Attribute Type')
    attribute_int = models.PositiveIntegerField('Int value', blank=True, null=True)
    attribute_string = models.CharField('Name', max_length=100, blank=True, null=True)

    def __unicode__(self):
        return 'Attribute: (' + self.crate.id + ')'

# Here is where the booking for a crate by a user is stored        
class Booking(models.Model):
    userid = models.CharField('User id', max_length=50)
    user_name = models.CharField('User name', max_length=50)
    user_email = models.CharField('User email', max_length=75, blank=True, null=True)
    crate = models.ForeignKey(Crate, verbose_name='Crate id')
    name = models.CharField('Name', max_length=100)
    timestamp = models.DateTimeField()
    start = models.DateTimeField()
    end = models.DateTimeField()
    reference = models.CharField('Reference', max_length=100, unique=True)
    link = models.CharField('Link', max_length=300, blank=True, null=True)
    cancelled = models.BooleanField('Cancelled', blank=True)
    cancelled_userid = models.CharField('Cancelled userid', max_length=50, blank=True, null=True)
    cancelled_user_name = models.CharField('Cancelled user name', max_length=50, blank=True, null=True)
    cancelled_timestamp = models.DateTimeField(blank=True, null=True)
    approved_userid = models.CharField('Approved userid', max_length=50, blank=True, null=True)
    approved_user_name = models.CharField('Approved user name', max_length=50, blank=True, null=True)
    pending = models.BooleanField('Requiring Approval', blank=True)

    class Meta:
        ordering = ['start']

    def __unicode__(self):
        return 'Booking: (' + self.crate.id + ',' + self.userid + ')'

class BookingType(models.Model):
    id = models.CharField('Type id', max_length=30, primary_key=True)
    parent = models.ForeignKey('self', blank=True, null=True)
    short_name = models.CharField('Short name (32 max)', max_length=32)
    name = models.CharField('Name', max_length=100)
    description = models.TextField('Description', max_length=2000, blank=True, null=True)
    
    def __unicode__(self):
        return self.id
        
class BookingTypeTree():
    # booking_type - current BookingType
    # parents - ordered list of crates leading to current crate
    # children - list of 'BookingTypeTree's
    def __init__(self,booking_type):
        # set target crate for view
        self.booking_type = booking_type
        self.children = self.build_tree_list(booking_type)

    # return a list of BookingTypeTrees starting from 'type' BookingType
    def build_tree_list(self, type):
        type_children = BookingType.objects.filter(parent_id=type.id)
        children = []
        for type_child in type_children:
            children.append(BookingTypeTree(type_child))
        
        return children
        
    def parents(self):
        # collect parents of this target
        p = []
        parent = self.booking_type.parent
        while parent:
            p.append(parent)
            parent = parent.parent
        
        p.reverse()
        return p

class CrateTree():
    # crate - current Crate
    # parents - ordered list of crates leading to current crate
    # children - list of 'CrateTree's
    def __init__(self,crate):
        # set target crate for view
        self.crate = crate
        self.children = self.build_tree_list(crate)

    # return a list of CrateTrees starting from 'top' crate
    def build_tree_list(self, top):
        top_crates = Crate.objects.filter(parent_crate_id=top.id)
        children = []
        for crate in top_crates:
            children.append(CrateTree(crate))
        
        return children
        
    def parents(self):
        # collect parents of this target
        p = []
        parent = self.crate.parent_crate
        while parent:
            p.append(parent)
            parent = parent.parent_crate
        
        p.reverse()
        return p

# Recents contains the most recent crates viewed by this user
class Recents(models.Model):
    userid = models.CharField('User id', max_length=50, primary_key=True)
    recent_crates_json = models.CharField('Recent crates list JSON', max_length=500)
    
    def __unicode__(self):
        return self.userid + ',' + self.recent_crates_json
        
# update the Recents data for this user
# Recents contains the most recent crates viewed by this user
def update_recents(userid, crate):
    try:
        r = Recents.objects.get(userid=userid)
        recents_list = json.loads(r.recent_crates_json)
    except Recents.DoesNotExist:
        r = Recents(userid, "") 
        recents_list = []
    new_recents_list = [ crate.id ]
    for crate_id in recents_list:
        if len(new_recents_list) < 10 and crate_id != crate.id:

templates/bookings/booking_detail.html
{% extends "base.html" %}

{% block title %}CBS: Booking {{ booking.crate.short_name }} on {{ booking.start|date:"D d M Y H:i" }}{% endblock %}

{% block local_logo %}{% endblock %}

{% block app_name %}Cambridge Booking System{% endblock %}

{% block breadcrumbs %}
<li>/ <a href="{% url 'index' %}">Bookings</a></li>
<li>/ Booking: {{ booking.crate.short_name }} on {{ booking.start|date:"D d M Y H:i" }}</li>
{% endblock %}

{% block subject_title %}
    {{ booking.name }}
 {% endblock %}
 
{% block content %}

{% include "bookings/booking_summary.html" %}

{% endblock %}
 

templates/bookings/booking_type_tree.html
            <li><a href="{% url 'crate' 'Au311' %}">{{ target.booking_type.name }}</a>
            {% if target.children %}
                <ul>
                {% for sub_tree in target.children %}
                    {% with target=sub_tree template_name="bookings/booking_type_tree.html" %}
                        {% include template_name %}
                    {% endwith %}
                {% endfor %}
                </ul>
            {% endif %}
            </li>

templates/bookings/comment_detail.html
{% extends "base.html" %}

{% block title %}CBS: Comment for {{ comment.crate.short_name }} on {{ comment.timestamp|date:"D d M Y H:i" }}{% endblock %}

{% block local_logo %}{% endblock %}

{% block app_name %}Cambridge Booking System{% endblock %}

{% block breadcrumbs %}
<li>/ <a href="{% url 'index' %}">CBS</a></li>
<li>/ Comment: {{ comment.user_name }} on {{ comment.timestamp|date:"D d M Y H:i" }}</li>
{% endblock %}

{% block subject_title %}
    {{ comment.crate.name }}
 {% endblock %}
 
{% block content %}

{% include "bookings/comment_summary.html" %}

{% endblock %}
 

templates/bookings/comment_form.html
{% comment %}
Presents a comment form for a crate

Assumes incoming vars:

form: class CommentForm
crate : current crate

{% endcomment %}            
                <!-- Comment form -->
                <form action="{% url 'comment' 1 %}" method="post">
                    {% csrf_token %}
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    <div class="fieldWrapper">
                        {{ form.startdate.errors }}
                        <textarea id="id_text"
                            cols="80" 
                            rows="1"
                            name="text"
                        ></textarea>
                    </div>
                    <div class="fieldWrapper">
                        {{ form.index.errors }}
                        Pin:<input id="id_pin" name="pin" type="checkbox" value="pin"/>
                        <p style="display: inline;"><input type="submit" value="Add this comment" /></p>
                    </div>
                    <input type="hidden" name="crate_id" value="{{ crate.id }}" />
                    <input type="hidden" name="action" value="ADD" />
                    <input type="hidden" name="user_name" value="{{ cam_user }}" />
                    
                </form>
                <!-- end of comment form -->

templates/bookings/crate_booking_form.html
{% comment %}
Presents a single-row booking form for a crate

Assumes incoming vars:

form: class ShortBookingForm
crate : current crate

{% endcomment %}            
                <!-- Booking form -->
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.errors }}
                    {{ form.non_field_errors }}
                    {% if requires_approval %}
                    Request
                    {% else %}
                    Add
                    {% endif %} new booking:
                    <div class="fieldWrapper shortbookingfield">
                        {{ form.startdate.errors }}
                        <input id="id_startdate{{ ref }}" class="booking_startdate"
                            maxlength="12" 
                            size="7"
                            name="startdate"
                            style="color: #bbb" 
                            type="text" 
                            value="Date:" 
                            onfocus="if(this.value==this.defaultValue) { this.style.color='#000'; this.value='';}" 
                        />
                    </div>
                    <div class="fieldWrapper shortbookingfield">
                        {{ form.starttime.errors }}
                        <input id="id_starttime{{ ref }}" class="booking_starttime"
                            maxlength="12" 
                            size="6"
                            name="starttime"
                            style="color: #bbb" 
                            type="text" 
                            value="Start:" 
                            onfocus="if(this.value==this.defaultValue) { this.style.color='#000'; this.value='';}" 
                        />
                    </div>
                    <div class="fieldWrapper shortbookingfield">
                        {{ form.duration.errors }}
                        <input id="id_duration{{ ref }}" class="booking_duration"
                            maxlength="6" 
                            size="6"
                            name="duration"
                            style="color: #bbb" 
                            type="text" 
                            value="Length:" 
                            onfocus="if(this.value==this.defaultValue) { this.style.color='#000'; this.value='';}" 
                        />
                    </div>
                    <div class="fieldWrapper shortbookingfield">
                        {{ form.name.errors }}
                        <label for="id_name">Title:</label>
                        <input id="id_name" maxlength="40" size="40" name="name" type="text" />
                    </div>
                    <input type="hidden" name="crate_id" value="{{ crate.id }}" />
                    <input type="hidden" name="crate_name" value="{{ crate.name }}" />
                    {% if requires_approval %}
                    <input type="hidden" name="calendar_id" value="{{ crate.provisional_calendar_id }}" />
                    <input type="hidden" name="pending" value='1' />
                    <p style="display: inline;"><input type="submit" name="crate_booking_form" value="Request Booking" /></p>
                    {% else %}
                    <input type="hidden" name="calendar_id" value="{{ crate.calendar_id }}" />
                    <input type="hidden" name="pending" value='0' />
                    <p style="display: inline;"><input type="submit" name="crate_booking_form" value="Book this" /></p>
                    {% endif %}
                </form>
                <!-- end of booking form -->

templates/bookings/crate_list.html
{% extends "base.html" %}

{% load ra_templatetags %}

{% block title %}CBS: List{% endblock %}

{% block local_logo %}{% endblock %}

{% block app_name %}Cambridge Booking System{% endblock %}

{% block breadcrumbs %}
<li>/ <a href="{% url 'index' %}">Bookings</a></li>
<li>/ List</li>
{% endblock %}

{% block subject_title %}
List
{% endblock %}

{% block content %}
    <ul>
        {% for target in crate_list %}
            {% include "bookings/crate_tree.html" %}
        {% endfor %}
    </ul>
{% endblock %}

templates/bookings/crate_stats.html
{% extends "base.html" %}

{% block head_block %}
	<script>
        $(document).ready( function () {
            $("#tabs").tabs( "option", "active", 7 );
        });
    </script>
    
  {% include "bookings/stats_header.html" %}

{% endblock %}

{% block title %}{{ crate_tree.crate.name }} Calendars{% endblock %}

{% block local_logo %}{% endblock %}

{% block breadcrumbs %}
<li>/ <a href="{% url 'index' %}">UIS Room Calendars</a></li>
<li>/ Stats: {{ crate_tree.crate.name }}</li>
{% endblock %}

{% block subject_title %}
    <ul class='parents'>
        <li><a href="{% url 'index' %}">UIS Room Calendars</a> &gt;</li>
    {% for crate in parents %}
        <li><a href="{% url 'crate' crate.id %}">{{ crate.name }}</a> &gt;</li>
    {% endfor %}
    </ul>
    {{ crate_tree.crate.name }}
 {% endblock %}
 
{% block content %}

<!-- Tabs -->
<div id="tabs">
	<ul class='cam_tabs'>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#calendar">Calendar</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#details">Details</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#map">Map</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#comments">Comments</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#bookings">Bookings</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#pending">Requests</a></li>
		<li class="newpage"><a href="{% url 'crate' crate_tree.crate.id %}#settings">Settings</a></li>
		<li><a href="#stats">Usage</a></li>
        {% if cbs_debug %}
		<li style="float: right;"><a href="#cbs_debug">Dev debug info</a></li>
        {% endif %}
	</ul>
    <div id="stats">
    </div>
    {% if cbs_debug %}
    <!-- debug info -->
    <div id="cbs_debug">
        <p>Nothing fancy, some debug info for the Crate Stats tab...</p>
        <ul>
        {% for d in cbs_debug %}
            <li>{{ d }}
            </li>
        {% endfor %}
        </ul>
    </div>
    <!-- end debug -->
    {% endif %}
</div> <!-- end of Tabs -->

<!--
<div id="monthly_chart" style="width: 95%; height: 600px"></div>
<p>[<a href="javascript:view_data(uupm_data)">View raw monthly data</a>]
</p>
-->
<div id="daily_chart" style="width: 95%; height: 600px"></div>
<p>[<a href="javascript:view_data(uupd_data)">View raw daily data</a>]
</p>

{% endblock %}
 

templates/bookings/crate_tree.html
            <li><a href="{% url 'crate' target.crate.id %}">{{ target.crate.name }}</a>
            {% if target.children %}
                <ul>
                {% for sub_tree in target.children %}
                    {% with target=sub_tree template_name="bookings/crate_tree.html" %}
                        {% include template_name %}
                    {% endwith %}
                {% endfor %}
                </ul>
            {% endif %}
            </li>

templates/bookings/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% comment %}
########################################################################
This template allows customization of the page via:
  home_title: title for page
  home_top: HTML for top content section
  home_menu: left menu
  insts: will create 'recent resources' list as left menu
  recent_crates: will create 'recent resources' list as left menu
  home_bottom: HTML for bottom content section
########################################################################
{% endcomment %}

{% block local_logo %}{% endblock %}

{% block breadcrumbs %}
<li>/ UIS Room Calendars</li>
{% endblock %}

{% block content %}
<!-- start CONTENT block -->
<!-- HOME_TITLE -->
{% if site.home_title %}
    {{ site.home_title|safe }}
{% else %}
    <h2>Welcome to the UIS Room Calendar System</h2>
{% endif %}
<!-- end HOME_TITLE -->

<!-- HOME_TOP -->
{% if site.home_top %}
    {{ site.home_top|safe }}
{% else %}
    <p>This website could best be described as an experiment. The initial objective was simply to
    provide an easy way to view and update the Google calendars for each of the meeting rooms
    in the <a href="{% url 'crate' 'RNB' %}">Roger Needham Building</a>.
    </p>
    
    <center><h2><a href="{% url 'crate' 'RNB' %}">Roger Needham Building Calendars</a></h2>
    <center><h2><a href="{% url 'crate' 'Cockcroft' %}">Cockcroft Building Calendars</a></h2>
    <br/><br/><br/><hr/><br/><br/><p>This menu below is for development purposes only...</p>
{% endif %}
<!-- END HOME TOP -->
<!-- HOME_MENU block -->
{% if home_menu %}
    {{ home_menu }}
{% else %}
    <div class='cam_list_container'>
        <div class='cam_list_header'>
            <h2>Menu options</h2>
        </div>
        <ul class='cam_list'>
            {% for inst in insts %}
                <li><a href="{% url 'inst' inst.instid %}">Browse {{ inst.name }}</a></li>
            {% endfor %}
            <li><a href="{% url 'insts' %}">Browse all Departments/Colleges</a></li>
            <li><a href="{% url 'crates' %}">Browse all resources</a></li>
            <li><a href="{% url 'person' cam_userid %}">View your information</a></li>
            <li>Find room availability for a particular date</li>
            <li><a href="http://www.doodle.com/polls/wizard.html" target="_blank">Schedule an event via doodle.com</a>
            <!-- <li><a href="http://carrier.csi.cam.ac.uk:83/admin/bookings/crate/add/">Add bookable resource</a></li> -->
            <!-- <li><a href="http://carrier.csi.cam.ac.uk:83/admin/bookings/crate/">Change the settings for a particular item</a></li> -->
            <li><a href="{% url 'stats' %}">View usage stats for this system</a></li>
        </ul>
    </div>
{% endif %}
<!-- END HOME_MENU -->

{% if recent_crates or insts %}
<!-- optional HOME_RECENTS list -->
<div class='cam_list_container'>
    <div class='cam_list_header'>
        <h2>Your recent resources</h2>
    </div>
    <ul class='cam_list'>
    {% for crate in recent_crates %}
        <li><a href="{% url 'crate' crate.id %}">{{ crate.name }}</a></li>
    {% endfor %}
    </ul>
</div>
<!-- end HOME_RECENTS list -->
{% endif %}

<!-- HOME_BOTTOM -->
{% if site.home_bottom %}
    {{ site.home_bottom|safe }}
{% endif %}
<!-- END HOME BOTTOM -->

<!-- end CONTENT block -->
{% endblock %}


templates/bookings/inst_stats.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ target.name }} Calendars{% endblock %}

{% block head_block %}
	<script>
        $(document).ready( function () {
            $("#tabs").tabs( "option", "active", 4 );
        });
    </script>
    
  {% include "bookings/stats_header.html" %}

{% endblock %}

{% block local_logo %}{% endblock %}

{% block breadcrumbs %}
<li>/ <a href="{% url 'index' %}">UIS Room Calendars</a></li>
<li>/ Stats: {{ target.name }}</li>
{% endblock %}

{% block subject_title %}
    {{ target.name }}
 {% endblock %}
 
{% block content %}

<!-- Tabs -->
<div id="tabs">
	<ul>
		<li class="newpage"><a href="{% url 'inst' target.instid %}#crates">Resources</a></li>
		<li class="newpage"><a href="{% url 'inst' target.instid %}#details">Details</a></li>
		<li class="newpage"><a href="{% url 'inst' target.instid %}#comments">Comments</a></li>
		<li class="newpage"><a href="{% url 'inst' target.instid %}#bookings">Bookings</a></li>
		<li><a href="#stats">Usage Stats</a></li>
	</ul>
    <div id="stats">
    </div>
</div> <!-- end of Tabs -->

<div id="monthly_chart" style="width: 95%; height: 600px"></div>
<p>[<a href="javascript:view_data(uupm_data)">View raw monthly data</a>]
</p>

<div id="daily_chart" style="width: 95%; height: 600px"></div>
<p>[<a href="javascript:view_data(uupd_data)">View raw daily data</a>]
</p>


{% endblock %}
 

templates/bookings/rule_summary.html

{% comment %}######################################################
#
# Display a single rule with optional 'delete' button.
#
# Input context:
# 'rule' : Rule object to display
# 'rule_delete_action': Boolean switch to display 'Delete' button
#
###################################################{% endcomment %} 

<div style="background-color: rgb(242,255,255);
            padding: 5px;
            border-radius: 12px;
            margin: 5px;
            ">
  {% if rule_delete_action %}
  <div style="float: right;">
      <form action="{% url 'crate' rule.crate.id %}" method="post" style='display: inline; text-align: right;'>
        {% csrf_token %}
        <input type='hidden' name='action' value='DELETE' />
        <input type='hidden' name='rule_id' value='{{ rule.id }}' />
        <input type="submit" value="Delete this rule" />
      </form>
  </div>
  {% endif %}
  <div>
  <div>
  <p>For <a href="{% url 'crate' rule.crate.id %}">{{ rule.crate.name }}</a> and any resources within.<br/>
  {{ rule.permission.name }} permission granted to:<br/>
  {% if rule.instid %}<a href="{% url 'inst' rule.instid %}">Inst {{ rule.instid }}</a>{% endif %}
  {% if rule.userid %}Userid {{ rule.userid }}{% endif %}
  {% if rule.groupid %}<a href="http://www.lookup.cam.ac.uk/group/{{ rule.groupid }}/members">Lookup group {{ rule.groupid }}</a>{% endif %}
  {% if rule.permission.description %}({{ rule.permission.description }}){% endif %}
  </p>
  </div>

</div>    